// Generated by `npm run system` from design/system.yaml: change the record, not this file.
// The Google Fonts stylesheet for the record's families, or "" when every
// family is a system font or self-hosted (@font-face in styles/input.css).
export const googleFontsUrl = "https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:wght@600;700&family=Inter:wght@400;600&display=swap";
